apiVersion: {{ include "networkpolicyversion" . }}
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Ingress to the Shoot's Kubernetes API Server from pods labeled with 'networking.gardener.cloud/to-shoot-apiserver=allowed'
      and Prometheus, and Egress to etcd pods.
  name: allow-kube-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: kubernetes
      garden.sapcloud.io/role: controlplane
      role: apiserver
  egress:
  - to:
    # Allow connection to shoot's etcd instances.
    - podSelector:
        matchLabels:
          app: etcd-statefulset
          garden.sapcloud.io/role: controlplane
    ports:
    - protocol: TCP
      port: {{ .Values.etcdServicePort }}
  {{- if .Values.konnectivityTunnel.enabled }}
  - to:
    # Allow connections from the apiserver pod to itself (i.e., konnectivity-server to apiserver)
    - podSelector:
        matchLabels:
          role: apiserver
          garden.sapcloud.io/role: controlplane
    ports:
      - protocol: TCP
        port: {{ required ".securePort is required" .Values.securePort }}
  {{- end }}
  {{- if .Values.vpaEnabled }}
  - to:
    # Allow connections from the apiserver pod to the vpa-admission-controller
    - podSelector:
        matchLabels:
          app: vpa-admission-controller
    ports:
    - protocol: TCP
      port: 10250
  {{- end }}
  ingress:
    # Allow connection from everything which needs to talk to the API server
  - from:
    # allow all other Pods in the Seed cluster to access it.
    - podSelector: {}
    # kube-apiserver can be accessed from anywhere using the LoadBalancer.
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: {{ required ".securePort is required" .Values.securePort }}
    {{- if .Values.konnectivityTunnel.enabled }}
    - protocol: TCP
      port: {{ required ".konnectivityTunnel.agentPort is required" .Values.konnectivityTunnel.agentPort }}
    {{- end }}
  - from:
    - podSelector:
        matchLabels:
          app: prometheus
          garden.sapcloud.io/role: monitoring
          role: monitoring
    {{- if .Values.konnectivityTunnel.enabled }}
    # Allow connections from the apiserver pod to itself (i.e., konnectivity-server to apiserver)
    - podSelector:
        matchLabels:
          role: apiserver
          garden.sapcloud.io/role: controlplane
    {{- end}}
    ports:
    - protocol: TCP
      port: {{ required ".blackboxExporterPort is required" .Values.blackboxExporterPort }}
    - protocol: TCP
      port: {{ required ".securePort is required" .Values.securePort }}
  policyTypes:
  - Egress
  - Ingress
